const express = require("express")
const app = express()
const bodyParser = require("body-parser")
const cors = require("cors")
const vacations = require("./routes/vacations")
const users = require("./routes/users")
const VaildateToken = require("./validations/tokenValidations")
const verify = require("./routes/verify")
const follow = require("./routes/follow")
require("dotenv").config()

const port = process.env.PORT || 4000
app.listen(port, () => console.log(`now listening to port ${port}`))
app.use(bodyParser.json())
app.use(cors())

app.use("/users", users)
app.use("/verify", verify)
app.use(VaildateToken)
app.use("/vacations", vacations)
app.use("/follow", follow)
