export default {
    REGISTER:"REGISTER",
    LOGIN:"LOGIN",
    LOGOUT:"LOGOUT",
    VACATIONS:"VACATIONS",
    RESET_REDIRECT:"RESET_REDIRECT",
    GET_TOKEN:"GET_TOKEN",
    VALIDATED_STATUS:"VALIDATED_STATUS"
}