export default {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    VACATIONS: "VACATIONS",
    RESET_REDIRECT: "RESET_REDIRECT",
    FOLLOWERS:"FOLLOWERS",
    VALIDATED_STATUS: "VALIDATED_STATUS"
}